### PR TITLE
Resolve a few development-related issues

### PR DESCRIPTION
**Pull request by sidonath**
Gems should specify their dependencies in the .gemspec file, not Gemfile, unless the gem—during active development—needs to reference non-released gems.

A gem should never publish its Gemfile lock, as gems need work with versions of gems bundled with the app.

The gem was relying on an old version of Minitest. Let's bring it up to date to avoid warnings and make it compatible with projects that use latest version of Minitest.

### CODE REVIEW

**Comment by sidonath** [comment]
https://trello.com/c/Y4E9sJEB/1825-enhancements-to-stathat-ruby-library

**Review by wam — APPROVED** [review]
😎

**Review by jjb — COMMENTED** [review]
we're not going to distribute this as a gem so i'm a bit wary of doing all this stuff right now. if/when they start to accept our changes, then we can ask them if they are interested in these types of changes as well.

the only thing that is affecting our ability to dev is the rake thing, right?

let's keep this PR around for a couple weeks and see what we hear back from stathat. i'm guessing that someone is on vacation.

**Comment by jjb** [comment]
[Enhancements to stathat gem and dev configuration](https://trello.com/c/SiRAOLOE/836-enhancements-to-stathat-gem-and-dev-configuration)

**Comment by jjb** [comment]
> if/when they start to accept our changes

> let's keep this PR around for a couple weeks and see what we hear back from stathat

😭 🙃 😱

**Comment by sidonath** [comment]
Hahaha, took me too much time to understand what was going on here 😂

**Pull request closed without merging**
