### PR TITLE
Accomodate new success behavior

### PR DESCRIPTION
**Pull request by jjb**

### CODE REVIEW

**Comment by jjb** [comment]
[Enhancements to stathat ruby library](https://trello.com/c/Y4E9sJEB/1825-enhancements-to-stathat-ruby-library)

**Comment by sidonath** [comment]
Oh, wow, great catch of exceptions happening in threads! 👏 

Can we remove usages of `pp` instead of adding the library?

**Review by sidonath — APPROVED** [review]

**Comment by jjb** [comment]
> Can we remove usages of pp instead of adding the library?

I considered that, but I am trying to possibly appease the maintainer, if he ever gives me attention.

**Comment by jjb** [comment]
but you know what, we can cross that bridge when we come to it. i'll replace it with puts.

**Pull request merged**
